### ISSUE TITLE
Change sets for arrays

### ISSUE THREAD

**Issue by meyer1994** [meyer1994/regular#18]
Should we change the sets for arrays?

The chagen is supposed to be done only in the classes attributes. Not in the code itself, where it is used in some algorithms.

PROS:
- Easier GUI development
- No need for conversions like `Array.from()` and `set.values()`

CONS:
- Some loss of performance in Chrome for the `set.has()`
- Considerable code refactoring needed

**Comment by geovanij2** [comment]
yes we should. Set in javascript wasn't doing us any favor

**Comment by meyer1994** [comment]
Refactored and changed in fafa27d947f98994d833f3a538ac6da26c2b3102
